table=int(input("Enter the value for the table"))
print(f"{table}*1={table}")
print(f"{table}*2={2*table}")
print(f"{table}*3={table*3}")
print(f"{table}*4={table*4}")
print(f"{table}*5={table*5}")
print(f"{table}*6={table*6}")
print(table)